name: "Opened Issue Automation"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "status: accepted"
